[project]
name = "duplicate-images"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nils von Norsinski", email = "nilsvonnorsinski@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "imagehash>=4.3.2",
]

[project.scripts]
duplicate-images = "duplicate_images:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
